services:
  metool:
    #build: .
    image: roenoe/metool
    volumes:
      - metool_db:/app/db
    command: [ "/usr/local/bin/entrypoint.sh" ]
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - metool
    restart: always

volumes:
  metool_db:
