services:
  metool:
    image: node
    # Use a bind mount to sync the local project directory with the container's /app folder
    # This means any changes you make locally will be immediately available in the container
    volumes:
      - .:/app
      # The database volume is still defined to persist your data
      - metool_db:/app/db

    # Set the working directory inside the container
    # This is where the application's code will be located
    working_dir: /app

    # Overwrite the default container command to install dependencies and run the application
    entrypoint: sh -c "chmod +x startup.sh && ./startup.sh"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - metool
    restart: always

volumes:
  metool_db:
